# Generated by Django 5.2.11 on 2026-04-06 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'permissions': [('manageRoles', 'Can manage all user roles'), ('manageConnections', 'Can manage connections and trigger connector runs'), ('viewAuditLog', 'Can view the audit log'), ('createUsers', 'Can create new user accounts')]},
        ),
    ]
