# Generated by Django 5.2.11 on 2026-04-17 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Budget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("budget_id", models.IntegerField(unique=True)),
                ("name", models.CharField(max_length=255)),
                ("department_head", models.CharField(max_length=255)),
                (
                    "group",
                    models.CharField(
                        choices=[
                            ("department", "Department"),
                            ("committee", "Committee"),
                        ],
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BudgetItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_id", models.IntegerField()),
                ("description", models.CharField(max_length=255)),
                ("category", models.CharField(blank=True, max_length=100, null=True)),
                ("gl_account", models.IntegerField(blank=True, null=True)),
                (
                    "gl_description",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "annual_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("fiscal_year", models.IntegerField(blank=True, null=True)),
                (
                    "budget",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="budgets.budget",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("budget", "item_id"), name="uniq_budget_item"
                    )
                ],
            },
        ),
    ]
